# SHA1:d135ec03fb355be3b73c1f26b70016916778a8ed
#
# This file is autogenerated by pip-compile-multi
# To update, run:
#
#    pip-compile-multi
#
coverage[toml]==7.4.3
    # via pytest-cov
exceptiongroup==1.2.0
    # via pytest
execnet==2.0.2
    # via pytest-xdist
iniconfig==2.0.0
    # via pytest
numpy==1.26.4
    # via
    #   pandas
    #   pyarrow
packaging==23.2
    # via pytest
pandas==2.2.1
    # via -r basetest.in
pluggy==1.4.0
    # via pytest
psutil==5.9.8
    # via -r basetest.in
pyarrow==15.0.0
    # via -r basetest.in
pytest==8.0.2
    # via
    #   -r basetest.in
    #   pytest-asyncio
    #   pytest-cov
    #   pytest-xdist
pytest-asyncio==0.23.5
    # via -r basetest.in
pytest-cov==4.1.0
    # via -r basetest.in
pytest-xdist==3.5.0
    # via -r basetest.in
python-dateutil==2.9.0.post0
    # via pandas
pytz==2024.1
    # via pandas
six==1.16.0
    # via python-dateutil
tomli==2.0.1
    # via
    #   coverage
    #   pytest
tzdata==2024.1
    # via pandas
